### ISSUE TITLE
[DatabaseApp] Именование

### ISSUE THREAD

**Issue by pavel-b-novikov** [VishnevKirill/nsudotnet#1]
Абсолютно адское. Прочитайте гайдлайн в лекциях, или на сайте MS (Class library Development Guidelines/Manimg Guidelines) и переименуйте. 
Таблицы в MSSQL - сюрприз - тоже называются PascalCase - ом. А ID превращается в Id.

**Comment by VishnevKirill** [comment]
Учтём, исправим

**Comment by VishnevKirill** [comment]
Поскольку основные силы были  брошены на GUI, При полном переименовании возникали проблемы с миграциями + база была уже заполнена, было решено не изменять именования в DAL.

**Comment by pavel-b-novikov** [comment]
Ну.. ладно
