### ISSUE TITLE
[DatabaseApp] Функциональность

### ISSUE THREAD

**Issue by pavel-b-novikov** [VishnevKirill/nsudotnet#2]
Крайне бедная.
Вы хоть формочку редактирования-добавления добавьте. Ну хоть к одной сущности. А то у вас команда вроде в модели есть (неправильно поименованная), а нигде не используется.

**Comment by VishnevKirill** [comment]
Извините, заключительный коммит сегодня в 22.00. Всё будет.

**Comment by VishnevKirill** [comment]
Функциональность расширена, Теперь Есть CRUD на 3 сущности + несколько запросов для  корректного редактирования. Проблема с именованием решена частично, т.к надо переименовывать всю базу. Возможно мы попытаемся сегодня решить эту проблему

**Comment by pavel-b-novikov** [comment]
Это конечно пичаль, но зато работает
