### ISSUE TITLE
[DatabaseApp] Всякие мелочи

### ISSUE THREAD

**Issue by pavel-b-novikov** [VishnevKirill/nsudotnet#3]
Итак, как вы заметили, в рамках приложений на подобном стеке частенько возникают определенные сложности и нестыковки, которые ставят в тупик многих разработчиков. Поэтому я приведу их тут сразу же и предложу вам придумать и написать решение на несколько подобных ситуаций в рамках существующей архитектуры. При придумывании решений вы можете пользоваться любыми фичами языка/технологии/другими фреймворками. Главное чтобы было изящно, легко реализовать и имело минимум сайд-эффектов (в смысле чтобы приложение - желательно - не надо было полностью перетестировать). Итак, погнали.

Кейс 1: списки для комбобоксов. Естественно, тянуть их из БД, как у вас делается, каждый раз не вариант. Предложите что с ними делать, чтобы обращаться к БД реже. Помните, что списки могут меняться.

Кейс 2: Локализация. Есть заказчики, которым необходимо переключать языки в приложении прямо во время работы. Ну.. в общем такие правда есть - поверьте мне на слово. Что вы можете им предложить?

Кейс 3: Опишите в нескольких словах, как вы видите View-модели для отображения древовидных структур данных.

Кейс 4: Как вы собираетесь делать валидацию данных? Предложите что-то помимо IDataErrorInfo

Кейс 5: Бывает такое, что слой БД вам заменяет слой веб-сервисов, данные из которых имеют свойство приходить сами (пример: IM-клиент с сообщениями). Как вы будете организовывать слой логики поверх такого "реактивного" слоя данных?

**Comment by VishnevKirill** [comment]
Кейс 4:  Можно определить проверку достоверности на уровне привязки. Это обеспечивает гибкость для использования одной и той же проверки достоверности, независимо от элемента управления вводом. Еще лучше, что поскольку проверка достоверности определяется в отдельном классе, можно легко повторно использовать ее с множеством привязок, которые имеют дело с однотипными данными.

**Comment by VishnevKirill** [comment]
Также есть способ с выкидыванием exception, и их переопределением.

**Comment by VishnevKirill** [comment]
Кейс 5: Надо подумать.... первое что приходит на ум система eventов и listenerов Мы ловим события о обновлении на уровне данных, и оповещаем GUI который дёргает интерфейс, но тут как  бы цикл......

**Comment by VishnevKirill** [comment]
Кейс 2:  Для локализации можно использовать ресурсы. Здесь единицей локализации является XAML-файл (формально это скомпилированный BAML-pecypc, который встраивается в приложение). При желании поддерживать несколько различных языков, потребуется включить ровно столько же BAML-pecypcов. WPF будет выбирать из них подходящий на основании текущих настроек культуры на компьютере, на котором выполняется приложение. Ну, и желательно, чтобы приложение адекватно реагировало на изменение содержимого. То есть нужно грамотно устанавливать размеры так, чтобы они могли изменяться по мере необходимости. Так же подумать о шрифте.

**Comment by VishnevKirill** [comment]
Кейс1: Мы берем из бд списки по одному разу, преимущественно в конструкторах. Для того, чтобы каждый раз не обращаться к базе данных за предоставлением очередного списка (то есть вариации списка из уже имеющихся) предлагается просто данные фильтровать. Еще у нас есть случай, когда определенному товару соответствует свой список поставщиков. Тогда можно сделать отбор во время исполнения программы, но если список для данного товара уже генерировался, то подставлять именно его , а не лезть в базу данных снова(скорее всего нужно завести что-то вроде кэша списков, и хранить последние N списков для товаров ). А если какой-то из списков изменился - оповещать об этом.

**Comment by pavel-b-novikov** [comment]
Кейс 2: неа, не будет оно автоматически переключать.
Кстати, из какого свойства читается текущая локаль приложения?

**Comment by pavel-b-novikov** [comment]
Кейс1:

> предлагается просто данные фильтровать

а по-подробнее?

> (скорее всего нужно завести что-то вроде кэша списков, и хранить последние N списков для товаров)

Ну вот же, вот. Что мешает сделать кэш списков и для других наборов данных?

**Comment by pavel-b-novikov** [comment]
Кейс 5:

> тут как бы цикл

Нет тут цикла. Идея правильная. Копаем дальше.

**Comment by pavel-b-novikov** [comment]
> проверку достоверности на уровне привязки

Это как? Уж не собираетесь ли вы класс Binding переопределять?

**Comment by VishnevKirill** [comment]
Кейс 2: CultureInfo.CurrentCulture

**Comment by VishnevKirill** [comment]
Кейс 5: Необходимо ввести систему асинхронных методов Async/Await?

**Comment by pavel-b-novikov** [comment]
> Async/Await

Зачем? О_О Это-то тут при чем?

**Comment by VishnevKirill** [comment]
Да, не то.

**Comment by VishnevKirill** [comment]
Кейс 4: есть несколько довольно сложных фрэймворков, мы нашли про Wakidzashi. Его суть в том, что мы в коде вешаем атрибуты с ограничениями, а потом   перегружаем метод  Validate() для реакции. Там довольно много уже готовых шаблонов правил, и можно писать свои.

**Comment by pavel-b-novikov** [comment]
Кейс 4: принимается, хорошее решение. Единственная его сложность в том, что скоммутировать его с IoC для db-валидации достаточно сложно.

**Comment by VishnevKirill** [comment]
Kейс 5: Нужен конкретный framework?

**Comment by pavel-b-novikov** [comment]
Kейс 5: нет. нужно головой подумать.

**Comment by VishnevKirill** [comment]
Kейс 2: Там у WPF не очень удобно, есть такой вариант: написать синглтон который парсит xml  с локалями,  и поместить в нём Event(смена локали) и все окна подписать на этот event.  А обработчик просто запрашивает у класса локализации все необходимые строки.

**Comment by pavel-b-novikov** [comment]
Зачем парсить XML с локалями? Функциональности .resx вам не хватает?

**Comment by VishnevKirill** [comment]
Да, тоже верно, можно просто грузить оттуда.

**Comment by VishnevKirill** [comment]
Павел, нам на зачёт пора. Придём можем до отвечать.

**Comment by Aliuysha** [comment]
Для кейс 3. Нужен конкретный пример? Или прям в ооочень общих словах описать?

**Comment by pavel-b-novikov** [comment]
А помимо этих двух крайностей есть что-нибудь?

**Comment by Aliuysha** [comment]
Нужно просто попробовать сделать дерево из View-моделей. Вью-модель со списком, в котором такие же вью-модели (BindableCollection< <ThisViewModel> > Children)

**Comment by pavel-b-novikov** [comment]
Ага.
А вот теперь обстоятельство, которое убивает всех, кто пытается решить эту задачу.
У узла дерева, как правило, есть плюсик. Маленький такой. И вот короче он должен появляться, если у модели в базе данных есть дети и исчезать если их нету. При том, как вы понимаете, тянуть из БД все, что лежит ниже по иерархии - не вариант.

**Comment by Aliuysha** [comment]
Есть такая еще штука TreeView - часто применяются для размещения больших объемов данных.  TreeView обладает сворачиваемо-разворачиваемой структурой. Если делать прокрутку TreeView пользователем сверху донизу, видимой не обязательно будет вся доступная в нем информация. Невидимая информация может вообще пропускаться, при этом сокращая накладные расходы (и время, необходимое для его заполнения). Еще при открытии элемента TreeViewItem инициируется событие Expanded, а при закрытии — событие Collapsed. Этот момент очень удобно использовать для добавления недостающих узлов или удаления тех, что уже больше не нужны

**Comment by pavel-b-novikov** [comment]
Я вам не про контролы сейчас, а про ViewModel.

**Comment by VishnevKirill** [comment]
Кейс 5: возникла такая архитектура: в логике есть метод который слушает вход, и возвращает event по типу события , GUI ловит его и запускает обработчик который уже вытягивает данные.

**Comment by pavel-b-novikov** [comment]
Кейс 5: ну в общем и целом принимается. Только реализуется это на C#-евентах обычно.

**Comment by VishnevKirill** [comment]
так, а 2 принят?

**Comment by pavel-b-novikov** [comment]
Неа. 
Что значит "подписать окна на изменения"?

**Comment by VishnevKirill** [comment]
имелось ввиду, что они получают это событие, и начинают вытягивать строки.

**Comment by pavel-b-novikov** [comment]
Как?

**Comment by VishnevKirill** [comment]
OpenFileMenu.Text = Localization.Instance.GetString("MainForm.MainMenu.File.Open");
SaveAsFileMenu.Text = Localization.Instance.GetString("MainForm.MainMenu.File.SaveAs");

**Comment by VishnevKirill** [comment]
например

**Comment by pavel-b-novikov** [comment]
Вы что, издеваетесь?

**Comment by VishnevKirill** [comment]
всмысле что долго?

**Comment by pavel-b-novikov** [comment]
В смысле что имея механизм привязок вы собираетесь вручную проставлять свойства?

**Comment by Aliuysha** [comment]
Кейс 3. Я так понимаю, вас интересует этот плюсик. Если у вью модели попытаться вытянуть первую строку или может быть есть метод проверки будет результат или нет. Если результат есть, то тогда на запрос экспандбл должно быть тру.  И плюсик должен появиться.

**Comment by pavel-b-novikov** [comment]
Кейс 3: Ага. А как быть с тем, что в другом окне могут добавить данные в этот узел? Через логику, разумеется. Не зная о том, что где-то есть узел дерева.

**Comment by VishnevKirill** [comment]
Так, а если binding сделать к ресурснику через название строки  а,  наш обработчик просто меняет её значение.

**Comment by pavel-b-novikov** [comment]
В ресурснике нельзя изменить значение в Runtime. Да и как-то надо быть с уведомлениями.

**Comment by Aliuysha** [comment]
Кейс 3. Реализовать паттерн Observable. Таким образом, когда происходит добавление, оповещаются все подписчики. Это делается с помощью event'ов

**Comment by VishnevKirill** [comment]
кейс 2: эм, не совсем понял проблему.

**Comment by pavel-b-novikov** [comment]
> Реализовать паттерн Observable.

Вы еще слишком молоды, чтобы кидаться настолько абстрактными инструкциями :) Конкретнее?

**Comment by pavel-b-novikov** [comment]
> эм, не совсем понял проблему.

Стандартный ResourceManager а) не позволяет менять строки в runtime б) не кидает никаких сообщений о том, что обновился

**Comment by Aliuysha** [comment]
В любом случае наш узел должен быть подписан на изменения у логики. Как только мы пытытытытаемся что-то изменить из логики, то логика говорит подписчикам, что её поменяли. Я не знаю, как конкретнее.

**Comment by pavel-b-novikov** [comment]
Ладно. Кейс 3 - с пивом покатит.
Но я еще раз предупреждаю, что иерархические ViewModel-и - очень, очень плохая идея.

**Comment by VishnevKirill** [comment]
Кейс2: вы хотите услышать про LocBaml?

**Comment by Aliuysha** [comment]
у Microsoft есть несколько способов локализации WPF приложений: локализация с помощью утилиты locbaml, с помощью resx файлов и с помощью xml. Мы уже рассказали вам про 2 варианта. Если говорить о 3-ем варианте, то можно запилить класс ResoursesLoader, который будет получать словарь для основной сборки, а если текущая культура отличается от той, которая по умолчанию, то грузим ресурсы текущей культуры

**Comment by Aliuysha** [comment]
Давайте немного подытожим. На что осталось ответить?

**Comment by pavel-b-novikov** [comment]
locbaml хороший вариант вполне. Ладно, кейс 2 - зачет.

**Comment by pavel-b-novikov** [comment]
> Давайте немного подытожим.

Остался кейс 1, но я уже уезжаю до академа ставить зачеты, так что черт с ним. В общем и целом вы все описали правильно. направление мысли присутствует и это главное.
